paths-ignore:
- packages/ingestion-sdk/src/__tests__/credit-card.test.ts
- packages/ingestion-sdk/src/__tests__/national-id.test.ts
- packages/ingestion-sdk/src/__tests__/policy.test.ts
- packages/ingestion-sdk/src/__tests__/*.test.ts
