# Firebase Environment Configuration for Zenithfall
# Generated by Terraform on deployment
# This file contains the Firebase configuration for cloud deployment

# Firebase Configuration
FIREBASE_PROJECT_ID=${project_id}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${project_id}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${firebase_config.authDomain}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${firebase_config.storageBucket}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${firebase_config.messagingSenderId}
NEXT_PUBLIC_FIREBASE_APP_ID=${firebase_config.appId}

# GCP Configuration
GCP_PROJECT_ID=${project_id}
GCP_REGION=${region}
FIRESTORE_PROJECT=${project_id}
FIRESTORE_DATABASE=(default)

# Tenant Configuration
TENANT=zenithfall
TENANT_ID=zenithfall
TENANT_TIER=development

# Cloud URLs
API_URL=${api_url}
NEXT_PUBLIC_API_URL=${api_url}

# Storage Configuration
STORAGE_BUCKET=${storage_bucket}
UPLOADS_BUCKET=${uploads_bucket}
FIREBASE_STORAGE_BUCKET=${firebase_config.storageBucket}

# Firebase Features
FIREBASE_AUTH_ENABLED=true
FIRESTORE_ENABLED=true
FIREBASE_STORAGE_ENABLED=true
FIREBASE_ANALYTICS_ENABLED=false
FIREBASE_HOSTING_ENABLED=true

# Security Configuration
FIREBASE_ANONYMOUS_AUTH=true
FIREBASE_EMAIL_AUTH=true
FIREBASE_MFA_ENABLED=false

# Application Configuration
NODE_ENV=production
CORS_ORIGIN=${api_url},https://${project_id}.web.app,https://${project_id}.firebaseapp.com

# Vector Database Configuration (Hybrid Mode)
VECTOR_DB_MODE=hybrid
VECTOR_DIM=384
EMBEDDINGS_PROVIDER=vertex

# LLM Configuration
LLM_ENABLED=true
LLM_PROVIDER=openai
LLM_MODEL=gpt-4-1106-preview
LLM_STREAMING=true
LLM_TIMEOUT_MS=25000

# Rate Limiting (Cloud Configuration)
RATE_LIMIT_PER_IP=100
RATE_LIMIT_PER_USER=1000
RATE_LIMIT_PER_TENANT=10000
RATE_LIMIT_WINDOW_MINUTES=1

# Timeout Configuration (Cloud Optimized)
VECTOR_SEARCH_TIMEOUT_MS=8000
KEYWORD_SEARCH_TIMEOUT_MS=5000
RERANKER_TIMEOUT_MS=15000
OVERALL_TIMEOUT_MS=60000
EMBEDDING_TIMEOUT_MS=8000

# Answerability Guardrail Configuration
ANSWERABILITY_THRESHOLD=0.01

# Tenant Branding Configuration
TENANT_BRAND_NAME=Zenithfall RAG
TENANT_LOGO_URL=/logos/zenithfall-logo.png
TENANT_PRIMARY_COLOR=#059669
TENANT_SECONDARY_COLOR=#10b981
TENANT_THEME=production

# Development vs Production Toggle
HYBRID_MODE=true
LOCAL_FALLBACK=false